services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - frontend-dist:/app/dist
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "8888:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - frontend-dist:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

volumes:
  frontend-dist:

networks:
  app-network:
    driver: bridge
